name: Build Nuxt App for IIS

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Zvol prostředí pro deploy'
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install    

      - name: Build Nuxt app for IIS
        run: npx nuxi build --preset=iis_node

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: nuxt-iis-output-${{ github.run_id }}
          path: ./.output 

    deploy:
      needs: build
      if: ${{ github.event_name == 'workflow_dispatch' }}
      runs-on: ${{ inputs.environment == 'production' && 'production-runner' || 'local-runner' }}

      steps:
        - name: Stáhni artefakt
          uses: actions/download-artifact@v4
          with:
            name: nuxt-iis-output
            path: ./deploy

        - name: Deploy na IIS
          shell: pwsh
          run: |
            $source = "$(Resolve-Path ./deploy)"
            $destination = "C:\TestDeploy\nuxt-app"
            if (!(Test-Path $destination)) { New-Item -ItemType Directory -Path $destination }
            Copy-Item "$source\*" "$destination" -Recurse -Force                 
