name: Build Nuxt App for IIS and Upload Artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt app for IIS
        run: npx nuxi build --preset=iis_node

      - name: Debug – Find .output on Windows
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Directory -Filter ".output"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-iis-output
          path: .output
