name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Zvol prostředí pro deploy'
        required: true
        type: choice
        options:
          - staging
          - production
      build_id:
        description: 'Zadej ID buildu (např. run_id z CI buildu)'
        required: true

jobs:
  deploy:
    runs-on: ${{ inputs.environment == 'production' && 'production-runner' || 'local-runner' }}

    steps:
      - name: Stáhni artefakt
        uses: actions/download-artifact@v4
        with:
          name: nuxt-iis-output-${{ inputs.build_id }}
          path: ./deploy

      - name: Deploy na IIS
        shell: pwsh
        run: |
          $source = "$(Resolve-Path ./deploy)"
          $destination = "C:\TestDeploy\nuxt-app"
          if (!(Test-Path $destination)) { New-Item -ItemType Directory -Path $destination }
          Copy-Item "$source\*" "$destination" -Recurse -Force